export const STARTER_DECK = [
  {
    position_name: 'Toreando defense',
    category: 'guard_retention',
    situation: "Tu es en guard ouverte. L'adversaire grab tes deux chevilles et initie un toreando pass vers ta droite.",
    answer: "Aligner tes hanches dans la même direction que tes jambes (si pieds à droite, hanches tournent à droite). Genoux serrés près des côtes. Pieds actifs sur ses hanches ou biceps. Ne PAS tirer les jambes vers toi.",
    cues: 'Pense "mes hanches suivent mes pieds". Jamais les épaules à plat.',
    grappling_link: "Le toreando est le pass #1 en no-gi. Tes pieds et tes hanches sont tes seuls outils sans grips.",
    video_url: 'https://submeta.io/@lachlangiles/courses/open-guard-retention',
    source: 'starter',
  },
  {
    position_name: 'Knee shield insertion',
    category: 'half_guard_bottom',
    situation: "L'adversaire commence un knee cut pass. Son genou glisse entre tes jambes. Tu es en train de perdre la half guard.",
    answer: "Insérer le knee shield AVANT qu'il s'installe. Genou au sternum, pied sur la hanche opposée. Ton tibia crée une barrière infranchissable.",
    cues: "À 198cm, ton tibia est une barre de fer. Plus tôt tu insères, mieux c'est.",
    grappling_link: "Le knee cut est le pass #1 en no-gi. Le knee shield est ta réponse #1 en half guard.",
    video_url: 'https://submeta.io/@lachlangiles/courses/half-guard-bottom',
    source: 'starter',
  },
  {
    position_name: 'Side control escape plan A',
    category: 'escapes',
    situation: "Tu es en side control subi. L'adversaire a le crossface et le underhook. Il est lourd sur toi.",
    answer: "1) Frames : avant-bras sur la gorge + main sur la hanche. 2) Bridge par-dessus l'épaule LOIN du crossface. 3) Shrimp dans l'espace créé. 4) Insérer le genou pour recover half guard ou full guard.",
    cues: "Bridge d'abord pour créer l'espace, shrimp ensuite pour le récupérer. Jamais l'inverse.",
    grappling_link: "C'est l'escape que tu utiliseras le plus. Bridge = espace, shrimp = recovery, genou = protection.",
    video_url: 'https://submeta.io/@lachlangiles/courses/pin-escapes',
    source: 'starter',
  },
  {
    position_name: 'Mount escape : plan A et B',
    category: 'escapes',
    situation: "Tu es en montée subi. L'adversaire est stable, mains au sol, poids sur toi.",
    answer: "Plan A : frame avec le coude en travers du visage + explosion pour créer l'espace. Plan B (si A échoue) : trap un bras + le pied du même côté, bridge par-dessus l'épaule opposée (upa). Plan C : elbow-knee escape, shrimp un genou à travers.",
    cues: "Essaie le frame d'abord (ta technique). Si bloqué, passe au trap arm + bridge. Deux options empêchent l'adversaire de se préparer.",
    grappling_link: "Avoir 2-3 options depuis la même position te rend imprévisible. Un seul move = prévisible = contrôlable.",
    video_url: 'https://submeta.io/@lachlangiles/courses/pin-escapes',
    source: 'starter',
  },
  {
    position_name: 'Back defense priorités',
    category: 'escapes',
    situation: "L'adversaire a tes crochets et le seatbelt. Sa main glisse sous ton menton pour le RNC.",
    answer: "Priorité #1 : protéger le cou (2 sur 1 sur sa main d'attaque). Priorité #2 : éliminer le crochet du côté où tu vas sortir. Priorité #3 : tourner VERS lui pour arriver en guard, pas en s'éloignant.",
    cues: "Menton au sternum, mains au cou. Tu connais le 2 sur 1, c'est exactement ici que tu l'utilises.",
    grappling_link: "Tu te fais prendre le dos régulièrement. Le 2 sur 1 des mains que tu maîtrises est la solution directe.",
    video_url: 'https://submeta.io/@lachlangiles/courses/back-escapes',
    source: 'starter',
  },
  {
    position_name: 'Half guard : underhook = la clé',
    category: 'half_guard_bottom',
    situation: "Tu es en half guard bottom avec le knee shield en place. L'adversaire pousse ton genou pour s'installer.",
    answer: "Obtenir le underhook du côté du knee shield. Dès que tu l'as : tourne sur ta hanche, lève-toi en sit-up. De là : single leg, back take, ou John Wayne sweep.",
    cues: "Le knee shield c'est la porte. Le underhook c'est la clé. Sans underhook, le knee shield finit par tomber.",
    grappling_link: "Tu connais le John Wayne mais pas le système qui y mène. Le underhook est le lien manquant.",
    video_url: 'https://submeta.io/@lachlangiles/courses/half-guard-bottom',
    source: 'starter',
  },
  {
    position_name: 'Whizzle counter → back take',
    category: 'half_guard_bottom',
    situation: "Tu as le underhook depuis la half guard. L'adversaire whizzle (overhook) ton bras pour le neutraliser.",
    answer: "Ne lutte PAS contre le whizzle. Change de plan : duck under (passe ta tête sous son bras) pour prendre le dos directement.",
    cues: "Le whizzle est un cadeau déguisé. Insister sur le sweep = perdre. Changer d'angle = gagner.",
    grappling_link: "C'est le type d'arbre de décision qui manque à ton jeu bottom : si A bloqué, passe à B au lieu de forcer A.",
    video_url: 'https://submeta.io/@lachlangiles/courses/half-guard-bottom',
    source: 'starter',
  },
  {
    position_name: 'Seated guard vs snap down',
    category: 'guard_retention',
    situation: "Tu es assis en guard, l'adversaire debout. Il attrape ta tête et pousse vers le bas (snap down).",
    answer: "Ne PAS poster les mains au sol. Frames sur ses épaules/biceps, hanches qui reculent, pieds qui se reconnectent à ses hanches. Si tu tombes en arrière, garde les pieds actifs en guard ouverte. Jamais turtle.",
    cues: "Mains qui frament, hanches qui reculent. Poster les mains = perdre les frames = guard s'effondre.",
    grappling_link: "C'est le scénario classique : snap down → guard passée → turtle → back take → soumission.",
    video_url: 'https://submeta.io/@lachlangiles/courses/open-guard-retention',
    source: 'starter',
  },
  {
    position_name: 'Turtle : hand fighting avant sit-out',
    category: 'turtle',
    situation: "Tu es en turtle. L'adversaire a un seatbelt grip et essaie de mettre les crochets.",
    answer: "Priorité : hand fighting sur le bras qui passe sous ton aisselle. 2 sur 1 sur ce bras, coude serré au corps. ENSUITE seulement : sit-out vers le côté du underhook pour faire face, ou Peterson roll.",
    cues: "Tu as 3-5 secondes avant que les crochets rentrent. Le hand fighting AVANT le sit-out réduit l'effort.",
    grappling_link: "Tu connais le sit-out mais ça te coûte trop d'énergie. Le hand fighting en amont change tout.",
    video_url: 'https://submeta.io/@lachlangiles/courses/turtle-escapes',
    source: 'starter',
  },
  {
    position_name: 'John Wayne → top half → finish pass',
    category: 'half_guard_bottom',
    situation: "Tu as réussi le John Wayne sweep. Tu arrives en top half guard. L'adversaire a encore ta jambe.",
    answer: "Ne te précipite pas. Établis la pression : tête collée à sa joue (crossface), hanche basse. Tripod sur les orteils pour augmenter la pression. Extrais ta jambe en backstep. Si ça bloque : switch vers knee cut.",
    cues: "Tu connais la pression en tripode et le knee-elbow pass. C'est ici que tu les connectes.",
    grappling_link: "Ça relie ton jeu bottom (John Wayne) à ton jeu top (tripode + pass). Le pont entre les deux mondes.",
    video_url: 'https://submeta.io/@lachlangiles/courses/half-guard-passing',
    source: 'starter',
  },
]
