// Mobility exercises seed data (client-side fallback + reference)
// Canonical data lives in Supabase mobility_exercises table

export const PRE_TRAINING_EXERCISES = [
  {
    phase_order: 1,
    name: 'Cat-Cow',
    name_fr: 'Cat-Cow',
    category: 'spine_wakeup',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '5-6 cycles',
    default_hold_sec: null,
    is_bilateral: false,
    cue_pourquoi: 'Lubrification intervertébrale. Max 7-8 cycles (McGill).',
    cue_comment: 'Inspirer en extension, expirer en flexion. Mouvement lent et contrôlé.',
    cue_focus: 'Sentir chaque segment vertébral bouger indépendamment.',
    grappling_why: 'Prep colonne pour rotations au sol.',
  },
  {
    phase_order: 2,
    name: 'Dead Bugs',
    name_fr: 'Dead Bugs',
    category: 'spine_wakeup',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '8 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Anti-extension : transverse + obliques activés.',
    cue_comment: 'Dos plaqué au sol. Bras et jambe opposés descendent lentement.',
    cue_focus: 'Zéro mouvement lombaire. Le core ne bouge pas.',
    grappling_why: 'Simule rétention de guard (core rigide, membres mobiles).',
  },
  {
    phase_order: 3,
    name: 'Standing Hip CARs',
    name_fr: 'Standing Hip CARs',
    category: 'hip_mobility',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '3-5 cercles',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Maintien ROM, liquide synovial, auto-évaluation.',
    cue_comment: 'Debout, un genou levé. Cercle le plus large possible sans compenser.',
    cue_focus: 'Chercher le plus grand cercle possible. Noter les points de friction.',
    grappling_why: 'Dextérité des jambes en guard.',
  },
  {
    phase_order: 4,
    name: '90/90 Hip Switches',
    name_fr: '90/90 Hip Switches',
    category: 'hip_mobility',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '8-10 transitions',
    default_hold_sec: null,
    is_bilateral: false,
    cue_pourquoi: 'Rotation interne + externe simultanée.',
    cue_comment: 'Assis, les deux genoux à 90°. Basculer d\'un côté à l\'autre.',
    cue_focus: 'Les genoux touchent le sol à chaque transition.',
    grappling_why: 'Guard retention, sweeps, leg locks.',
  },
  {
    phase_order: 5,
    name: 'Adductor Rock-Back',
    name_fr: 'Adductor Rock-Back',
    category: 'hip_mobility',
    routine_type: 'pre',
    default_sets: 2,
    default_reps: '8-10 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Adducteurs souvent négligés mais très chargés.',
    cue_comment: 'À quatre pattes, une jambe tendue sur le côté. Reculer les hanches.',
    cue_focus: 'Garder le dos neutre. Sentir l\'étirement intérieur de cuisse.',
    grappling_why: 'Closed guard squeeze, half guard hooks, sprawl.',
  },
  {
    phase_order: 6,
    name: 'Quadruped T-Spine Rotation',
    name_fr: 'Rotation T-Spine Quadrupède',
    category: 'multi_joint',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '8-10 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Rotation thoracique décharge les lombaires.',
    cue_comment: 'À quatre pattes, main derrière la tête. Rotation vers le ciel.',
    cue_focus: 'Rotation uniquement thoracique. Les hanches ne bougent pas.',
    grappling_why: 'Framing, underhooks, crossface defense.',
  },
  {
    phase_order: 7,
    name: "World's Greatest Stretch",
    name_fr: "World's Greatest Stretch",
    category: 'multi_joint',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '5 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: '5 zones en 1 mouvement.',
    cue_comment: 'Fente avant, coude vers le sol, puis rotation bras vers le ciel.',
    cue_focus: 'Chaque rep doit être meilleure que la précédente.',
    grappling_why: 'Fléchisseurs, adducteurs, thoracique, ischios, cheville.',
  },
  {
    phase_order: 8,
    name: 'Cossack Squat Transitions',
    name_fr: 'Transitions Cossack Squat',
    category: 'multi_joint',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '5-6 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Plan frontal sous-entraîné mais critique.',
    cue_comment: 'Squat latéral profond, transition d\'un côté à l\'autre.',
    cue_focus: 'Talon au sol, poitrine haute. Contrôler la descente.',
    grappling_why: 'Shrimping, guard passing, scrambles latéraux.',
  },
  {
    phase_order: 9,
    name: 'Walking Spiderman + Reach',
    name_fr: 'Walking Spiderman + Reach',
    category: 'dynamic_prep',
    routine_type: 'pre',
    default_sets: 1,
    default_reps: '5-6 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Chaîne cinétique complète, monte le cardio.',
    cue_comment: 'Fente avant marchée, rotation thoracique, bras vers le ciel.',
    cue_focus: 'Transition fluide. C\'est l\'échauffement final avant le training.',
    grappling_why: 'Transition mobilité → entraînement.',
  },
]

export const POST_TRAINING_EXERCISES = [
  {
    phase_order: 1,
    name: 'Half-Kneeling Hip Flexor + PPT',
    name_fr: 'Hip Flexor Half-Kneeling + PPT',
    category: 'static_stretch',
    routine_type: 'post',
    default_sets: 2,
    default_reps: null,
    default_hold_sec: 45,
    is_bilateral: true,
    cue_pourquoi: 'Combat le tilt antérieur (guard, seated).',
    cue_comment: 'Genou arrière au sol, serrer le fessier, basculer le bassin (PPT).',
    cue_focus: 'Le stretch vient du bassin, pas en poussant vers l\'avant.',
    grappling_why: 'Combat tilt antérieur (guard, seated).',
  },
  {
    phase_order: 2,
    name: 'Couch Stretch',
    name_fr: 'Couch Stretch',
    category: 'static_stretch',
    routine_type: 'post',
    default_sets: 2,
    default_reps: null,
    default_hold_sec: 45,
    is_bilateral: true,
    cue_pourquoi: 'Rectus femoris spécifique.',
    cue_comment: 'Pied arrière contre un mur/canapé, fente avant.',
    cue_focus: 'Contracter le fessier. Si c\'est trop intense, reculer du mur.',
    grappling_why: 'Rectus femoris spécifique.',
  },
  {
    phase_order: 3,
    name: '90/90 Static Hold',
    name_fr: '90/90 Hold Statique',
    category: 'static_stretch',
    routine_type: 'post',
    default_sets: 1,
    default_reps: null,
    default_hold_sec: 45,
    is_bilateral: true,
    cue_pourquoi: 'ER + IR, plus safe que pigeon sous fatigue.',
    cue_comment: 'Position 90/90, se pencher vers la jambe avant.',
    cue_focus: 'Respirer profondément. Laisser la gravité faire le travail.',
    grappling_why: 'ER + IR, plus safe que pigeon sous fatigue.',
  },
  {
    phase_order: 4,
    name: 'Supine Spinal Twist',
    name_fr: 'Twist Spinal Couché',
    category: 'static_stretch',
    routine_type: 'post',
    default_sets: 1,
    default_reps: null,
    default_hold_sec: 50,
    is_bilateral: true,
    cue_pourquoi: 'Décompression thoracolombaire.',
    cue_comment: 'Sur le dos, genoux d\'un côté, bras ouverts.',
    cue_focus: 'Épaules au sol. Laisser la gravité tourner le tronc.',
    grappling_why: 'Décompression thoracolombaire.',
  },
  {
    phase_order: 5,
    name: "Child's Pose + Lat Stretch",
    name_fr: "Child's Pose + Stretch Lats",
    category: 'static_stretch',
    routine_type: 'post',
    default_sets: 1,
    default_reps: null,
    default_hold_sec: 40,
    is_bilateral: true,
    cue_pourquoi: 'Lats → fascia thoracolombaire.',
    cue_comment: 'Position enfant, mains loin devant, puis décaler vers un côté.',
    cue_focus: 'Allonger les bras au maximum. Sentir le stretch latéral.',
    grappling_why: 'Lats → fascia thoracolombaire.',
  },
  {
    phase_order: 6,
    name: 'Supine Hamstring PNF',
    name_fr: 'PNF Ischios Couché',
    category: 'static_stretch',
    routine_type: 'post',
    default_sets: 1,
    default_reps: '3-5 cycles',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: '+10-15% ROM vs statique. Open guard.',
    cue_comment: 'Jambe levée avec sangle. Contract-relax : pousser 5s, relâcher, tirer plus loin.',
    cue_focus: 'Le gain se fait sur le relâchement post-contraction.',
    grappling_why: '+10-15% ROM vs statique. Open guard.',
  },
  {
    phase_order: 7,
    name: 'Dead Hang',
    name_fr: 'Dead Hang',
    category: 'decompression',
    routine_type: 'post',
    default_sets: 3,
    default_reps: null,
    default_hold_sec: 45,
    is_bilateral: false,
    cue_pourquoi: 'Traction axiale, réhydratation discale, grip no-gi.',
    cue_comment: 'Prise pronation, épaules actives (légère dépression scapulaire).',
    cue_focus: 'Se laisser aller. Respirer. Sentir la colonne s\'allonger.',
    grappling_why: 'Traction axiale, réhydratation discale, grip no-gi.',
  },
  {
    phase_order: 8,
    name: '90/90 Breathing',
    name_fr: 'Respiration 90/90',
    category: 'breathing',
    routine_type: 'post',
    default_sets: 1,
    default_reps: '5-10 cycles',
    default_hold_sec: null,
    is_bilateral: false,
    cue_pourquoi: 'Nerf vague, shift parasympathique.',
    cue_comment: 'Sur le dos, jambes sur une chaise (hanches et genoux à 90°). Inspirer 4s, expirer 8s.',
    cue_focus: 'Expiration longue. Sentir le rythme cardiaque ralentir.',
    grappling_why: 'Nerf vague, shift parasympathique.',
  },
]

export const MORNING_EXERCISES = [
  {
    phase_order: 1,
    name: 'Supine Pelvic Tilts',
    name_fr: 'Bascules Pelviennes Couchées',
    category: 'spine_wakeup',
    routine_type: 'morning',
    default_sets: 1,
    default_reps: '10 reps',
    default_hold_sec: null,
    is_bilateral: false,
    cue_pourquoi: 'Réveiller le bassin et les lombaires en douceur.',
    cue_comment: 'Sur le dos, genoux pliés. Basculer le bassin avant/arrière.',
    cue_focus: 'Mouvement minimal, contrôle maximal.',
    grappling_why: 'Contrôle pelvien pour le guard.',
  },
  {
    phase_order: 2,
    name: 'Single-Leg Knee-to-Chest',
    name_fr: 'Genou-Poitrine Unilatéral',
    category: 'spine_wakeup',
    routine_type: 'morning',
    default_sets: 1,
    default_reps: '10s',
    default_hold_sec: 10,
    is_bilateral: true,
    cue_pourquoi: 'Étirement lombaire + fléchisseur de hanche.',
    cue_comment: 'Tirer un genou vers la poitrine, l\'autre jambe tendue au sol.',
    cue_focus: 'Garder le bas du dos au sol.',
    grappling_why: 'Flexion de hanche pour guard.',
  },
  {
    phase_order: 3,
    name: 'Cat-Cow',
    name_fr: 'Cat-Cow',
    category: 'spine_wakeup',
    routine_type: 'morning',
    default_sets: 1,
    default_reps: '5-8 cycles',
    default_hold_sec: null,
    is_bilateral: false,
    cue_pourquoi: 'Lubrification intervertébrale matinale.',
    cue_comment: 'Inspirer en extension, expirer en flexion.',
    cue_focus: 'Lent et contrôlé. Réveiller la colonne.',
    grappling_why: 'Prep colonne pour la journée.',
  },
  {
    phase_order: 4,
    name: 'Sidelying Open Books',
    name_fr: 'Open Books Latéral',
    category: 'multi_joint',
    routine_type: 'morning',
    default_sets: 1,
    default_reps: '5 reps',
    default_hold_sec: null,
    is_bilateral: true,
    cue_pourquoi: 'Rotation thoracique douce au réveil.',
    cue_comment: 'Sur le côté, genoux empilés. Ouvrir le bras du dessus vers l\'arrière.',
    cue_focus: 'Suivre la main du regard. Ne pas forcer.',
    grappling_why: 'Rotation thoracique pour frames et underhooks.',
  },
  {
    phase_order: 5,
    name: "Child's Pose + Breathing",
    name_fr: "Child's Pose + Respiration",
    category: 'breathing',
    routine_type: 'morning',
    default_sets: 1,
    default_reps: null,
    default_hold_sec: 30,
    is_bilateral: false,
    cue_pourquoi: 'Étirement dos + activation parasympathique.',
    cue_comment: 'Position enfant, front au sol, respiration ventrale.',
    cue_focus: '5 respirations profondes. Intention pour la journée.',
    grappling_why: 'Calme et focus avant la journée.',
  },
]

export const ALL_EXERCISES = {
  pre: PRE_TRAINING_EXERCISES,
  post: POST_TRAINING_EXERCISES,
  morning: MORNING_EXERCISES,
}

export const ROUTINE_META = {
  pre: {
    label: 'Pre-training',
    labelFr: 'Pré-entraînement',
    duration: '11 min',
    color: 'blue',
    bgClass: 'bg-blue-50',
    borderClass: 'border-blue-200',
    textClass: 'text-blue-700',
    badgeClass: 'bg-blue-100 text-blue-700',
  },
  post: {
    label: 'Post-training',
    labelFr: 'Post-entraînement',
    duration: '12-15 min',
    color: 'green',
    bgClass: 'bg-green-50',
    borderClass: 'border-green-200',
    textClass: 'text-green-700',
    badgeClass: 'bg-green-100 text-green-700',
  },
  morning: {
    label: 'Matin',
    labelFr: 'Routine matinale',
    duration: '2.5 min',
    color: 'amber',
    bgClass: 'bg-amber-50',
    borderClass: 'border-amber-200',
    textClass: 'text-amber-700',
    badgeClass: 'bg-amber-100 text-amber-700',
  },
}
